[2024-09-11T10:38:37.889+0000] {processor.py:161} INFO - Started process (PID=281) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:38:37.891+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:38:37.904+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:38:37.900+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:38:37.932+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:38:37.923+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:38:37.935+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:38:37.995+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.133 seconds
[2024-09-11T10:39:08.040+0000] {processor.py:161} INFO - Started process (PID=288) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:39:08.048+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:39:08.055+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:39:08.054+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:39:08.067+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:39:08.064+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:39:08.069+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:39:08.100+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.070 seconds
[2024-09-11T10:39:38.198+0000] {processor.py:161} INFO - Started process (PID=295) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:39:38.200+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:39:38.203+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:39:38.203+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:39:38.212+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:39:38.209+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:39:38.213+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:39:38.242+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.054 seconds
[2024-09-11T10:39:59.383+0000] {processor.py:161} INFO - Started process (PID=302) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:39:59.384+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:39:59.387+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:39:59.387+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:39:59.399+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:39:59.397+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:39:59.400+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:39:59.429+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.055 seconds
[2024-09-11T10:40:29.589+0000] {processor.py:161} INFO - Started process (PID=309) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:40:29.590+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:40:29.593+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:40:29.593+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:40:29.602+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:40:29.600+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:40:29.603+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:40:29.630+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.050 seconds
[2024-09-11T10:40:52.804+0000] {processor.py:161} INFO - Started process (PID=316) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:40:52.805+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:40:52.808+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:40:52.808+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:40:52.820+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:40:52.818+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:40:52.822+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:40:52.858+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.063 seconds
[2024-09-11T10:41:22.978+0000] {processor.py:161} INFO - Started process (PID=323) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:41:22.980+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:41:22.982+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:41:22.982+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:41:22.992+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:41:22.990+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:41:22.993+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:41:23.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.051 seconds
[2024-09-11T10:41:41.105+0000] {processor.py:161} INFO - Started process (PID=324) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:41:41.108+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:41:41.111+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:41:41.111+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:41:41.122+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:41:41.120+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:41:41.124+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:41:41.151+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.054 seconds
[2024-09-11T10:42:11.285+0000] {processor.py:161} INFO - Started process (PID=331) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:42:11.287+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:42:11.291+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:42:11.290+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:42:11.299+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:42:11.297+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:42:11.301+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:42:11.327+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.050 seconds
[2024-09-11T10:42:41.460+0000] {processor.py:161} INFO - Started process (PID=338) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:42:41.463+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:42:41.467+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:42:41.466+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:42:41.477+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:42:41.473+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:42:41.479+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:42:41.505+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.054 seconds
[2024-09-11T10:43:11.659+0000] {processor.py:161} INFO - Started process (PID=345) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:43:11.661+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:43:11.664+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:43:11.664+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:43:11.674+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:43:11.671+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:43:11.676+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:43:11.703+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.054 seconds
[2024-09-11T10:43:41.882+0000] {processor.py:161} INFO - Started process (PID=352) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:43:41.884+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:43:41.888+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:43:41.887+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:43:41.895+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:43:41.893+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:43:41.897+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:43:41.923+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.050 seconds
[2024-09-11T10:44:12.061+0000] {processor.py:161} INFO - Started process (PID=359) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:44:12.063+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:44:12.066+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:44:12.066+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:44:12.075+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:44:12.073+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:44:12.076+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:44:12.107+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.054 seconds
[2024-09-11T10:44:42.241+0000] {processor.py:161} INFO - Started process (PID=366) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:44:42.243+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:44:42.248+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:44:42.247+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:44:42.257+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:44:42.255+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:44:42.259+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:44:42.292+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.062 seconds
[2024-09-11T10:45:12.464+0000] {processor.py:161} INFO - Started process (PID=373) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:45:12.465+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:45:12.468+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:45:12.468+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:45:12.476+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:45:12.474+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:45:12.477+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:45:12.505+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.050 seconds
[2024-09-11T10:45:42.658+0000] {processor.py:161} INFO - Started process (PID=379) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:45:42.660+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:45:42.663+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:45:42.663+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:45:42.672+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:45:42.669+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:45:42.673+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:45:42.699+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.050 seconds
[2024-09-11T10:46:12.844+0000] {processor.py:161} INFO - Started process (PID=386) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:46:12.846+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:46:12.849+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:46:12.849+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:46:12.858+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:46:12.855+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:46:12.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:46:12.885+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.049 seconds
[2024-09-11T10:54:02.297+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:54:02.298+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:54:02.302+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:54:02.301+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:54:02.309+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:54:02.307+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:54:02.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:54:02.342+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.054 seconds
[2024-09-11T10:54:32.504+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:54:32.505+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:54:32.508+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:54:32.508+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:54:32.517+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:54:32.515+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:54:32.518+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:54:32.544+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.048 seconds
[2024-09-11T10:55:02.706+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:55:02.707+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:55:02.713+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:55:02.712+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:55:02.721+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:55:02.719+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:55:02.722+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:55:02.749+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.058 seconds
[2024-09-11T10:55:32.894+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:55:32.895+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:55:32.899+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:55:32.898+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:55:32.906+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:55:32.904+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:55:32.908+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:55:32.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.048 seconds
[2024-09-11T10:56:03.081+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:56:03.082+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:56:03.089+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:56:03.088+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:56:03.097+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:56:03.095+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:56:03.098+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:56:03.137+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.064 seconds
[2024-09-11T10:56:33.260+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:56:33.261+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:56:33.264+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:56:33.263+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:56:33.272+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:56:33.270+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:56:33.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:56:33.299+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.048 seconds
[2024-09-11T10:57:03.499+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:57:03.500+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:57:03.503+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:57:03.503+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:57:03.511+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:57:03.509+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:57:03.513+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:57:03.543+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.053 seconds
[2024-09-11T10:57:33.678+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:57:33.679+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:57:33.686+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:57:33.685+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:57:33.699+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:57:33.695+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:57:33.701+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:57:33.744+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.081 seconds
[2024-09-11T10:57:48.861+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:57:48.862+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:57:48.866+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:57:48.865+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:57:48.879+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:57:48.877+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:57:48.881+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:57:48.910+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.058 seconds
[2024-09-11T10:58:19.036+0000] {processor.py:161} INFO - Started process (PID=101) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:58:19.037+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:58:19.040+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:58:19.040+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:58:19.049+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:58:19.047+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:58:19.050+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:58:19.074+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.047 seconds
[2024-09-11T10:58:49.218+0000] {processor.py:161} INFO - Started process (PID=108) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:58:49.220+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:58:49.223+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:58:49.222+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:58:49.232+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:58:49.229+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:58:49.234+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:58:49.263+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.053 seconds
[2024-09-11T10:59:19.449+0000] {processor.py:161} INFO - Started process (PID=115) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:59:19.451+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:59:19.454+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:59:19.454+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:59:19.463+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:59:19.460+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:59:19.464+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:59:19.490+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.048 seconds
[2024-09-11T10:59:49.624+0000] {processor.py:161} INFO - Started process (PID=122) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:59:49.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T10:59:49.628+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:59:49.628+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:59:49.637+0000] {logging_mixin.py:188} INFO - [2024-09-11T10:59:49.635+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T10:59:49.638+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T10:59:49.664+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.048 seconds
[2024-09-11T11:00:19.804+0000] {processor.py:161} INFO - Started process (PID=129) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:00:19.806+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:00:19.808+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:00:19.808+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:00:19.816+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:00:19.814+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:00:19.817+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:00:19.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.047 seconds
[2024-09-11T11:00:49.974+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:00:49.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:00:49.979+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:00:49.978+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:00:49.987+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:00:49.985+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:00:49.988+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:00:50.015+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.050 seconds
[2024-09-11T11:01:20.155+0000] {processor.py:161} INFO - Started process (PID=143) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:01:20.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:01:20.160+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:01:20.159+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:01:20.169+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:01:20.166+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:01:20.170+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:01:20.195+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.049 seconds
[2024-09-11T11:01:50.328+0000] {processor.py:161} INFO - Started process (PID=150) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:01:50.332+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:01:50.335+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:01:50.335+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:01:50.343+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:01:50.341+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:01:50.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:01:50.372+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.052 seconds
[2024-09-11T11:02:20.513+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:02:20.515+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:02:20.518+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:02:20.518+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:02:20.527+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:02:20.525+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:02:20.529+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:02:20.558+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.054 seconds
[2024-09-11T11:02:50.747+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:02:50.749+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:02:50.752+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:02:50.751+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:02:50.761+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:02:50.758+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:02:50.762+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:02:50.796+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.061 seconds
[2024-09-11T11:03:20.917+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:03:20.918+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:03:20.921+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:03:20.921+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:03:20.931+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:03:20.928+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:03:20.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:03:20.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.052 seconds
[2024-09-11T11:03:51.126+0000] {processor.py:161} INFO - Started process (PID=178) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:03:51.128+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:03:51.131+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:03:51.130+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:03:51.139+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:03:51.137+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:03:51.140+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:03:51.165+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.051 seconds
[2024-09-11T11:05:26.737+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:05:26.739+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:05:26.744+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:05:26.743+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:05:26.752+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:05:26.749+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:05:26.753+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:05:26.789+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.066 seconds
[2024-09-11T11:05:56.964+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:05:56.965+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:05:56.968+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:05:56.968+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:05:56.978+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:05:56.975+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:05:56.980+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:05:57.013+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.057 seconds
[2024-09-11T11:06:27.138+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:06:27.139+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:06:27.142+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:06:27.142+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:06:27.150+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:06:27.148+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:06:27.151+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:06:27.178+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.049 seconds
[2024-09-11T11:06:57.333+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:06:57.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:06:57.338+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:06:57.337+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:06:57.349+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:06:57.347+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:06:57.350+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:06:57.379+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.055 seconds
[2024-09-11T11:07:27.511+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:07:27.512+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:07:27.514+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:07:27.514+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:07:27.522+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:07:27.519+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:07:27.523+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:07:27.549+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.046 seconds
[2024-09-11T11:07:57.758+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:07:57.760+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:07:57.763+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:07:57.762+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:07:57.771+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:07:57.768+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:07:57.772+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:07:57.798+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.050 seconds
[2024-09-11T11:08:28.006+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:08:28.007+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:08:28.012+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:08:28.012+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:08:28.029+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:08:28.027+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:08:28.031+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:08:28.155+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.165 seconds
[2024-09-11T11:08:58.438+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:08:58.440+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:08:58.443+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:08:58.443+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:08:58.451+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:08:58.449+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:08:58.453+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:08:58.480+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.051 seconds
[2024-09-11T11:09:28.624+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:09:28.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:09:28.628+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:09:28.628+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:09:28.636+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:09:28.634+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:09:28.638+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:09:28.665+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.050 seconds
[2024-09-11T11:09:58.819+0000] {processor.py:161} INFO - Started process (PID=101) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:09:58.821+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:09:58.824+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:09:58.823+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:09:58.832+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:09:58.829+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:09:58.833+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:09:58.864+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.054 seconds
[2024-09-11T11:10:29.044+0000] {processor.py:161} INFO - Started process (PID=108) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:10:29.045+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:10:29.049+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:10:29.048+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:10:29.059+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:10:29.056+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:10:29.060+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:10:29.087+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.051 seconds
[2024-09-11T11:10:59.253+0000] {processor.py:161} INFO - Started process (PID=115) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:10:59.255+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:10:59.259+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:10:59.259+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:10:59.270+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:10:59.267+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:10:59.272+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:10:59.310+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.066 seconds
[2024-09-11T11:11:29.435+0000] {processor.py:161} INFO - Started process (PID=122) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:11:29.438+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:11:29.444+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:11:29.443+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:11:29.458+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:11:29.455+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:11:29.460+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:11:29.503+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.084 seconds
[2024-09-11T11:11:59.821+0000] {processor.py:161} INFO - Started process (PID=129) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:11:59.823+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:11:59.828+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:11:59.828+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:11:59.838+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:11:59.835+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:11:59.840+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:11:59.873+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.064 seconds
[2024-09-11T11:12:30.029+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:12:30.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:12:30.033+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:12:30.032+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:12:30.041+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:12:30.039+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:12:30.043+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:12:30.078+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.060 seconds
[2024-09-11T11:13:00.247+0000] {processor.py:161} INFO - Started process (PID=143) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:13:00.248+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:13:00.253+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:13:00.252+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:13:00.262+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:13:00.259+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:13:00.263+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:13:00.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.054 seconds
[2024-09-11T11:13:30.416+0000] {processor.py:161} INFO - Started process (PID=150) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:13:30.418+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:13:30.421+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:13:30.421+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:13:30.429+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:13:30.427+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:13:30.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:13:30.463+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.055 seconds
[2024-09-11T11:14:00.585+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:14:00.586+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:14:00.589+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:14:00.589+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:14:00.597+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:14:00.595+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:14:00.598+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:14:00.625+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.048 seconds
[2024-09-11T11:14:30.937+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:14:30.942+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:14:30.962+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:14:30.960+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:14:30.983+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:14:30.980+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:14:30.984+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:14:31.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.252 seconds
[2024-09-11T11:15:01.340+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:15:01.342+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:15:01.352+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:15:01.351+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:15:01.369+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:15:01.366+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:15:01.370+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:15:01.435+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.116 seconds
[2024-09-11T11:18:53.692+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:18:53.696+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:18:53.707+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:18:53.705+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:18:53.722+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:18:53.717+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:18:53.724+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:18:53.812+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.148 seconds
[2024-09-11T11:19:24.058+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:19:24.062+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:19:24.078+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:19:24.077+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:19:24.103+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:19:24.094+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:19:24.105+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:19:24.397+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.379 seconds
[2024-09-11T11:19:54.938+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:19:54.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:19:55.040+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:19:55.015+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:19:55.115+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:19:55.105+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:19:55.129+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:19:55.379+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.568 seconds
[2024-09-11T11:20:25.618+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:20:25.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:20:25.628+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:20:25.628+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:20:25.639+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:20:25.636+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:20:25.640+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:20:25.672+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.062 seconds
[2024-09-11T11:20:55.784+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:20:55.786+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:20:55.788+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:20:55.788+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:20:55.796+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:20:55.794+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:20:55.797+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:20:55.842+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.066 seconds
[2024-09-11T11:22:32.156+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:22:32.160+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:22:32.168+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:22:32.167+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:22:32.185+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:22:32.179+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:22:32.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:22:32.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.087 seconds
[2024-09-11T11:23:02.315+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:23:02.317+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:23:02.321+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:23:02.320+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:23:02.329+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:23:02.327+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:23:02.330+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:23:02.357+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.050 seconds
[2024-09-11T11:23:32.497+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:23:32.498+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:23:32.504+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:23:32.503+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:23:32.512+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:23:32.509+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:23:32.513+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:23:32.543+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.055 seconds
[2024-09-11T11:29:44.203+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:29:44.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:29:44.233+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:29:44.230+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:29:44.264+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:29:44.247+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:29:44.267+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:29:44.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.253 seconds
[2024-09-11T11:30:14.599+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:30:14.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:30:14.603+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:30:14.603+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:30:14.611+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:30:14.609+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:30:14.613+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:30:14.640+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.049 seconds
[2024-09-11T11:30:44.791+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:30:44.793+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:30:44.796+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:30:44.795+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:30:44.804+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:30:44.802+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:30:44.805+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:30:44.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.057 seconds
[2024-09-11T11:31:14.962+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:31:14.964+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:31:14.967+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:31:14.966+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:31:14.975+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:31:14.972+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:31:14.976+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:31:15.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.049 seconds
[2024-09-11T11:31:45.133+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:31:45.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:31:45.137+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:31:45.137+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:31:45.144+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:31:45.142+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:31:45.146+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:31:45.173+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.047 seconds
[2024-09-11T11:32:15.304+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:32:15.305+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:32:15.308+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:32:15.308+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:32:15.316+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:32:15.314+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:32:15.317+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:32:15.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.047 seconds
[2024-09-11T11:32:45.500+0000] {processor.py:161} INFO - Started process (PID=86) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:32:45.501+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:32:45.505+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:32:45.504+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:32:45.513+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:32:45.511+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:32:45.515+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:32:45.545+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.054 seconds
[2024-09-11T11:33:15.670+0000] {processor.py:161} INFO - Started process (PID=93) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:33:15.672+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:33:15.675+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:33:15.675+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:33:15.683+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:33:15.681+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:33:15.684+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:33:15.710+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.048 seconds
[2024-09-11T11:39:32.641+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:39:32.643+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:39:32.646+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:39:32.646+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:39:32.657+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:39:32.654+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:39:32.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:39:32.691+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.059 seconds
[2024-09-11T11:40:02.902+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:40:02.903+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:40:02.906+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:40:02.906+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:40:02.914+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:40:02.912+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:40:02.915+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:40:02.941+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.048 seconds
[2024-09-11T11:40:33.068+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:40:33.069+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:40:33.072+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:40:33.072+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:40:33.079+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:40:33.077+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:40:33.080+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:40:33.104+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.043 seconds
[2024-09-11T11:41:03.249+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:41:03.251+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:41:03.256+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:41:03.255+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:41:03.268+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:41:03.265+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:41:03.270+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:41:03.319+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.081 seconds
[2024-09-11T11:41:33.416+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:41:33.431+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:41:33.434+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:41:33.434+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:41:33.445+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:41:33.442+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:41:33.446+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:41:33.473+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.065 seconds
[2024-09-11T11:42:03.720+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:42:03.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:42:03.725+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:42:03.725+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:42:03.737+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:42:03.733+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:42:03.739+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:42:03.807+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.105 seconds
[2024-09-11T11:42:33.891+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:42:33.893+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/databricks_apple_analysis_project.py for tasks to queue
[2024-09-11T11:42:33.895+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:42:33.895+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:42:33.903+0000] {logging_mixin.py:188} INFO - [2024-09-11T11:42:33.901+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/databricks_apple_analysis_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/databricks_apple_analysis_project.py", line 3, in <module>
    from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator
ModuleNotFoundError: No module named 'airflow.providers.databricks'
[2024-09-11T11:42:33.905+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/databricks_apple_analysis_project.py
[2024-09-11T11:42:33.932+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/databricks_apple_analysis_project.py took 0.049 seconds
